version: '2'

services:
  moe:
    image: frederikam/fred.moe:latest
    hostname: moe
    container_name: moe
    restart: always
    ports:
    - "80:80"
    - "443:443"
    - "2500:2500"
    environment:
    # This is required for automatic HTTPS! Setting this value
    # indicates that you agree to Let's Encrypt Subscriber Agreement.
    # No further action is required on your part
    - CADDY_EMAIL=
    # Also super important. The domain must be specified, otherwise fred.moe will only be readable on port 2500.
    # Example: example.org
    - DOMAIN=
    volumes:
    # By default your data will be mounted to ./moedata . Feel free to change this value, but keep the `:/home/data` part.
    - ./moedata:/home/data
  dev:
      image: frederikam/fred.moe:v2
      hostname: moe
      container_name: moe
      ports:
      - "80:80"
      - "443:443"
      - "2500:2500"
      environment:
      # This is required for automatic HTTPS! Setting this value
      # indicates that you agree to Let's Encrypt Subscriber Agreement.
      # No further action is required on your part
      - CADDY_EMAIL=""
      # Also super important. The domain must be specified, otherwise fred.moe will only be readable on port 2500.
      # Example: example.org
      - DOMAIN=
      volumes:
      # By default your data will be mounted to ./moedata . Feel free to change this value, but keep the `:/home/data` part.
      - ./moedata:/home/data
